### ISSUE TITLE
CLASH ROYALE

### ISSUE THREAD

**Issue by CGbRAWL** [MasterDevX/XCoder#8] opened 2019-07-23 21:02 UTC
Please add clash Royale compile

**Comment by MasterDevX** [comment] 2019-07-24 18:29
Closing as duplicate of https://github.com/MasterDevX/XCoder/issues/4
P.S. Currently I'm on vacation, so I'm not currently working on update, but I will some time later, stay tuned :)

**Closed as completed by MasterDevX** 2019-07-24 18:29 UTC
Labels: duplicate
